global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 3
  publish_frequency: 1
  static_map: true
  rolling_window: false
  resolution: 0.05
  transform_tolerance: 0.7
  plugins:
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,     type: "costmap_2d::VoxelLayer"}

