# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

topics:
-
  name    : navigation
  topic   : cmd_vel
  timeout : 0.1
  priority: 10
-
  name    : avoid
  topic   : avoid_vel
  timeout : 0.1
  priority: 90
-
  name    : keyboard
  topic   : key_vel
  timeout : 0.1
  priority: 110
-
  name    : move_before_grab
  topic   : /landrobot/move_before_grab
  timeout : 0.1
  priority: 101

